name: Node CI

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org/
            - name: npm install, build, and test
              run: |
                  npm ci
                  npm run build --if-present
                  npm test
                  npm publish --access public
              env:
                  CI: true
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
